env:
    MANIFEST: https://github.com/ArrowOS/android_manifest.git -b arrow-13.1
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt-1
    TARGET: bacon
    LUNCH_COMBO: arrow_${DEVICE}-userdebug
    OUTPUT: A*.zip
    CLO: 1:ci
    CLO_1: ENCRYPTED[9180e5cebc8ddd14f77750b368c01e239514fb2d0a1ae80878b1f1714a81384a21b730650636747cbe171a72d60fd653]
    URI: https://sourceforge.net/projects/fleur/files/ccache/Arrow/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
