env:
    MANIFEST: https://github.com/Evolution-X/manifest -b tiramisu-jem
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt-1
    TARGET: evolution 
    LUNCH_COMBO: evolution_${DEVICE}-userdebug
    OUTPUT: e*.zip
    CLO: ci:ci
    CLO_1: ENCRYPTED[78bf84ab4b7856641b2a5b15b99b69eaae5a594504bc4a35607fc3b5e79311e110d7eafec2eb94e4f0d15093beabf56d]
    URI: https://sourceforge.net/projects/fleur/files/ccache/EvoX/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
