env:
    MANIFEST: https://github.com/PixelOS-AOSP/manifest.git -b thirteen
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt-1
    TARGET: bacon
    LUNCH_COMBO: aosp_${DEVICE}-userdebug
    OUTPUT: P*.zip
    CLO: ci:ci
    CLO_1: ENCRYPTED[50fbac48b1d1b39552abb719bfdf898e70c1ebd58d07fc19096a5a6c340f64112ebb3d1e95dd9dd4e6717ef8cd53127b]
    URI: https://sourceforge.net/projects/fleur/files/ccache/Pixelos/ccache.tar.gz/download
    ROM_U: 1

task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 10
      memory: 40G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
