env:
    MANIFEST: https://github.com/RisingTechOSS/android -b thirteen --git-lfs
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt-1
    TARGET: bacon
    LUNCH_COMBO: lineage_${DEVICE}-userdebug
    OUTPUT: r*.zip
    CLO: ci:ci
    CLO_1: ENCRYPTED[aa2f1bbb14abe21af2757546154e29154daf201671e9c29a1c0ef24539534963ac756cda3d780d03ea11d78106555648]
    URI: https://sourceforge.net/projects/fleur/files/ccache/RisingOS/ccache.tar.gz/download
    ROM_U: 1

task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
