env:
    MANIFEST: https://github.com/PixelOS-AOSP/manifest.git -b thirteen
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifest-X01BD
    TARGET: bacon
    LUNCH_COMBO: aosp_${DEVICE}-userdebug
    OUTPUT: P*.zip
    CLO: ci:ci
    CLO_1: ENCRYPTED[3967d41e74a72efade74a9b23f8c32a708af3a54307ece0b23bf4ca94b251baef1505d0b7ff86864de8c14b6bf313cff]
    URI: https://sourceforge.net/projects/fleur/files/ccache/Pixelos/ccache.tar.gz/download
    ROM_U: 1

task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Swap_script:
      - ./scripts/SwAp || source scripts/SwAp
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
