env:
    MANIFEST: https://github.com/Evolution-X/manifest -b tiramisu-jem
    DEVICE: X01BD
    OEM: asus
    LOCAL_MANIFEST: https://github.com/RT1648/local_manifestt-1
    TARGET: evolution 
    LUNCH_COMBO: evolution_${DEVICE}-userdebug
    OUTPUT: e*.zip
    CLO: RMP:ci
    CLO_1: ENCRYPTED[86c2b8959430bd68a5630930f488dd1575435777f735aee2aff645ff98e49c7b9c8677559288f4e14ec2940e5b46adc0]
    URI: https://sourceforge.net/projects/fleur/files/ccache/EvoX/ccache.tar.gz/download
    ROM_U: 1
    
task:
  name: "build"
  timeout_in: 120m
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
  Storage-Checker_script:
      - ./scripts/d0wnl0ad
  Sync_script:
      - ./scripts/syn0
  Build_script:
      - ./scripts/bu1ld
  upload_script:
      - ./scripts/upl0ad
